#!/bin/bash
# This script uses the builtin "mapfile" and is only available in bash versions 4 and higher
# It also uses curl and mpv player
###############################################################
# Setup Text Colors
black=$(tput setaf 16)
white=$(tput setaf 15)
gray=$(tput setaf 236)
blue=$(tput setaf 21)
green=$(tput setaf 28)
red=$(tput setaf 1)
cyan=$(tput setaf 36)
purple=$(tput setaf 128)
brown=$(tput setaf 130)
yellow=$(tput setaf 226)
orange=$(tput setaf 202)
pink=$(tput setaf 207)
lgray=$(tput setaf 246)
lblue=$(tput setaf 39)
lgreen=$(tput setaf 118)
lred=$(tput setaf 9)
lcyan=$(tput setaf 14)
lpurple=$(tput setaf 99)

blgray=$(tput setab 246) # Background Light Gray

BoGreen=$(tput bold; tput setaf 28) # Bold Green
ReverseGR=$(tput setaf 28; tput rev) 	# Reverse Green

invis=$(tput civis)			# Invisible Cursor
norm=$(tput cnorm)			# Normal Cursor
standout=$(tput smso)
blink=$(tput blink)
reverse=$(tput rev)
bold=$(tput bold) 
reset=$(tput sgr0)      #  Reset text attributes to normal

###############################################################
tput clear

# Get the latest mp3 urls from aclj
urls=$(curl -s https://aclj.org/tune-in-to-our-live-radio-shows | grep -Pio '(?<=<\/a><\/h2><a href=").*?(?=" download style=)')

# Create an array from the urls to be used by the mpv player
mapfile -t < <(printf "%b\n" "${urls}") linesurl

#  Print the urls and pipe it to basename to get the date thats in the filename
dates=$(printf "%s\n" "${linesurl[@]}" | xargs -n1 basename -s .mp3 | sed 's/^....//')

# Create an array from the dates to use for the menu
mapfile -t < <(printf "%b\n" "${dates}") linesdates

printf "%b\n" "${purple}\n"
printf "%b\n" "https://aclj.org/tune-in-to-our-live-radio-shows\n"

printf "%b\n" "${red}"
printf "%b\n" "ACLJ Radio Show: Jay Sekulow Live\n"
# Display the Menu
printf "%b\n" "${green}"
printf "%b\n" "Select Your Date"

printf "%b\n" "${orange}"
printf "%b\n"
printf "%b\n" " 0. Jay Sekulow Live "${linesdates[0]}"\n" 
printf "%b\n" " 1. Jay Sekulow Live "${linesdates[1]}"\n"
printf "%b\n" " 2. Jay Sekulow Live "${linesdates[2]}"\n"
printf "%b\n" " 3. Jay Sekulow Live "${linesdates[3]}"\n"
printf "%b\n" " 4. Jay Sekulow Live "${linesdates[4]}"\n"
printf "%b\n" " 5. Jay Sekulow Live "${linesdates[5]}"\n"
printf "%b\n" " 6. Jay Sekulow Live "${linesdates[6]}"\n"
printf "%b\n" " 7. Jay Sekulow Live "${linesdates[7]}"\n"
printf "%b\n" " 8. Jay Sekulow Live "${linesdates[8]}"\n"
printf "%b\n" " 9. Jay Sekulow Live "${linesdates[9]}"\n"

printf "%b" "${invis}"

# Get the users selected date from the menu
read -r -n 1 choice

#  Assign the mp3 variable from the users choice
case ${choice} in

 0) mp3="${linesurl[0]}"
 ;;
 1) mp3="${linesurl[1]}"
 ;;
 2) mp3="${linesurl[2]}"
 ;;
 3) mp3="${linesurl[3]}"
 ;;
 4) mp3="${linesurl[4]}"
 ;;
 5) mp3="${linesurl[5]}"
 ;;
 6) mp3="${linesurl[6]}"
 ;;
 7) mp3="${linesurl[7]}"
 ;;
 8) mp3="${linesurl[8]}"
 ;;
 9) mp3="${linesurl[9]}"
 ;;
esac

printf "%b\n" "${reset}"
printf "%b\n" "${norm}"
tput cuu 27 # move the cursor up 27 lines
tput ed # clear the screen below the new cursor position

# Play the mp3 variable with mpv player
mpv "${mp3}"
